version: "3"

services:
  fastapi:
    container_name: fastapi_container
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    # volumes:
    #   - .:/app
    ports:
      - "8081:8000"
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:16.2
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER:-postgres}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpass}
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
